plugins {
    id 'com.android.library'
}

android {
    compileSdkVersion libs.versions.compile.sdk.version.get()
    namespace = 'org.twinlife.twinme'

    buildFeatures {
        buildConfig = true
    }
    defaultConfig {
        minSdkVersion libs.versions.min.sdk.version.get() as int
        targetSdkVersion libs.versions.target.sdk.version.get() as int
        buildConfigField "String", "VERSION", '"2.16.1"'

        buildConfigField "boolean", "ENABLE_REPORT_LOCATION", "false"
        buildConfigField "boolean", "DELETE_CONTACT_ON_UNBIND_CONTACT", "false"
    }

    flavorDimensions = ["product", "tier"]

    productFlavors {
        twinme {
            dimension "product"
        }
        skred {
            dimension "product"

            buildConfigField "boolean", "ENABLE_REPORT_LOCATION", "true"
            buildConfigField "boolean", "DELETE_CONTACT_ON_UNBIND_CONTACT", "true"
        }

        //Skred and Twinme
        free {
            dimension "tier"
        }

        //Twinme+
        '+' {
            dimension "tier"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        staging {
            initWith buildTypes.release
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'src/android/AndroidManifest.xml'
            java.srcDirs = ['src/main/java', 'src/android/java']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    testOptions {
        unitTests.all {
            useJUnitPlatform()
            maxHeapSize = '1G'
            testLogging {
                events "passed"
            }
        }
    }
}

androidComponents {
    // Only define necessary variants (Skred only has a free tier)
    beforeVariants(
            selector()
                    .withFlavor("product", "skred")
                    .withFlavor("tier", "+")
    ) { variantBuilder ->
        variantBuilder.enable = false
    }
}

dependencies {
    api fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':twinlife-framework')

    implementation libs.androidx.annotation
    implementation libs.zip4j
    testImplementation libs.junit.jupiter
}